name: Pre-commit Checks

on:
    push: # Trigger on every push to any branch
    pull_request: # Also run checks on pull requests to any branch

jobs:
    pre-commit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.9" # or another compatible version

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit

            - name: Run pre-commit hooks
              run: |
                  pre-commit install
                  pre-commit run --all-files
